name: Channel Update

on:
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
           node-version: 18

    - name: npm grab epg
      run: |
          npm install
          # npm run channels:parse --- --config=sites/starhubtvplus.com/starhubtvplus.com.config.js --output=sites/starhubtvplus.com/starhubtvplus.com_en.channels.xml --set=lang:en
          # npm run channels:parse -- --config=./sites/dishtv.in/dishtv.in.config.js --output=./sites/dishtv.in/dishtv.in_en.channels.xml --set=lang:en
          # npm run channels:parse -- --config=./sites/sky.com/sky.com.config.js --output=./sites/sky.com/sky.com.channels.xml
          # npm run channels:parse -- --config=./sites/tvpassport.com/tvpassport.com.config.js --output=./sites/tvpassport.com/tvpassport.com.channels.xml
          # npm run channels:parse -- --config=./sites/tvtv.us/tvtv.us.config.js --output=./sites/tvtv.us/tvtv.us.channels.xml
          # npm run channels:parse --- --config=./sites/content.astro.com.my/content.astro.com.my.config.js --output=./sites/content.astro.com.my/content.astro.com.my.channels.xml
          # npm run channels:parse -- --config=./sites/beinsports.com/beinsports.com.config.js --output=./sites/beinsports.com/beinsports.com_au-en.channels.xml --set=region:au --set=lang:en
          # npm run channels:parse --- --config=./sites/i.mjh.nz/i.mjh.nz.config.js --output=./sites/i.mjh.nz/i.mjh.nz_kayo.channels.xml --set=provider:kayo
          npm run channels:parse --- --config=./sites/epg.jesmann.com/epg.jesmann.com.config.js --output=./sites/epg.jesmann.com/epg.jesmann.com_unitedstates.channels.xml --set=tag:UnitedStates.xml.gz
    - name: Commit changes
      run: |
        git config --local user.email "your-email@example.com"
        git config --local user.name "Your Name"
        # git add -f sites/starhubtvplus.com/starhubtvplus.com_en.channels.xml
        # git add -f sites/dishtv.in/dishtv.in_en.channels.xml
        # git add -f sites/i.mjh.nz/i.mjh.nz_kayo.channels.xml
        # git add -f sites/tvpassport.com/tvpassport.com.channels.xml
        # git add -f sites/sky.com/sky.com.channels.xml
        git add -f sites/epg.jesmann.com/epg.jesmann.com_unitedstates.channels.xml
        git commit -a -m "Channel update"
        git push
