name: EPG Update

on:
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest
    env:
      PROXY_URL: ${{ secrets.PROXY_URL }}
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
          node-version: 22
          cache: 'npm'

    - name: npm grab epg
      run: |
          npm install
          npm run grab -- --site=dishtv.in --lang=en --maxConnections=10 --gzip --output=guides/dishtv.in_en.xml
          
    - name: Commit changes
      run: |
        git config --local user.email "your-email@example.com"
        git config --local user.name "Your Name"
        git add -f guides/dishtv.in_en.xml.gz
        git commit -m "Update xml"
        git push
